version: '3.9'

services:
  spring:
    build:
      context: .          # 上下文是项目根目录
      dockerfile: Dockerfile
    container_name: spring_app
    restart: always
    ports:
      - "8082:8082"
    depends_on:
      - redis

  nginx:
    image: nginx:stable
    container_name: nginx_frontend
    restart: always
    ports:
      - "8081:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/app   # 前端资源
    depends_on:
      - spring

  redis:
    image: redis:6.2
    container_name: redis_server
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
