version: '3.9'

services:
  spring:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: spring_app
    restart: always
    ports:
      - "8082:8082"            # 保留你原来的外部端口映射
    depends_on:
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile  # frontend/Dockerfile（见下）
    container_name: frontend_nginx
    restart: always
    ports:
      - "8081:80"              # 外部访问前端的端口（原先 nginx 映射 8081）
    depends_on:
      - spring

  redis:
    image: redis:6.2
    container_name: redis_server
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
